#pragma once

static const char INDEX_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>PirateBox</title>\n"
"<style>\n"
":root {\n"
"  --bg: #101216;\n"
"  --surface: #16181d;\n"
"  --surface-hover: #1c2027;\n"
"  --border: #262930;\n"
"  --border-light: #323742;\n"
"  --text: #e1e4ea;\n"
"  --text-muted: #798294;\n"
"  --text-dim: #545c6c;\n"
"  --btn-bg: #232730;\n"
"  --btn-text: #e1e4ea;\n"
"  --btn-border: #323742;\n"
"  --btn-primary-bg: #e1e4ea;\n"
"  --btn-primary-text: #101216;\n"
"  --danger: #c93b3b;\n"
"  --warn: #d97706;\n"
"  --mono: ui-monospace, \"SF Mono\", Menlo, Consolas, monospace;\n"
"}\n"
"* { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  background: var(--bg);\n"
"  color: var(--text);\n"
"  font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;\n"
"  font-size: 13px;\n"
"  line-height: 1.45;\n"
"  padding: 16px;\n"
"  max-width: 820px;\n"
"  margin: 0 auto;\n"
"}\n"
"header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: baseline;\n"
"  padding-bottom: 12px;\n"
"  border-bottom: 1px solid var(--border);\n"
"  margin-bottom: 12px;\n"
"}\n"
".brand {\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"  letter-spacing: 0.5px;\n"
"  color: #fff;\n"
"}\n"
".header-meta {\n"
"  font-family: var(--mono);\n"
"  font-size: 11px;\n"
"  color: var(--text-muted);\n"
"}\n"
"nav {\n"
"  display: flex;\n"
"  gap: 2px;\n"
"  background: var(--surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  margin-bottom: 12px;\n"
"}\n"
".nav-btn {\n"
"  flex: 1;\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: var(--text-muted);\n"
"  font-size: 12px;\n"
"  font-weight: 500;\n"
"  padding: 7px 10px;\n"
"  border-radius: 3px;\n"
"  cursor: pointer;\n"
"}\n"
".nav-btn.active {\n"
"  background: var(--btn-bg);\n"
"  color: var(--text);\n"
"}\n"
".tab { display: none; }\n"
".tab.active { display: block; }\n"
".card {\n"
"  background: var(--surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 4px;\n"
"  padding: 12px;\n"
"  margin-bottom: 12px;\n"
"}\n"
".card-title {\n"
"  font-weight: 600;\n"
"  font-size: 12px;\n"
"  color: #fff;\n"
"  margin-bottom: 8px;\n"
"  font-family: var(--mono);\n"
"  text-transform: uppercase;\n"
"  letter-spacing: 0.5px;\n"
"}\n"
".btn {\n"
"  background: var(--btn-bg);\n"
"  color: var(--btn-text);\n"
"  border: 1px solid var(--btn-border);\n"
"  border-radius: 3px;\n"
"  padding: 5px 10px;\n"
"  font-size: 12px;\n"
"  font-weight: 500;\n"
"  cursor: pointer;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  white-space: nowrap;\n"
"}\n"
".btn-primary {\n"
"  background: var(--btn-primary-bg);\n"
"  color: var(--btn-primary-text);\n"
"  border-color: var(--btn-primary-bg);\n"
"  font-weight: 600;\n"
"}\n"
".btn-danger {\n"
"  color: var(--danger);\n"
"  border-color: rgba(201, 59, 59, 0.4);\n"
"}\n"
".btn-danger:hover {\n"
"  background: rgba(201, 59, 59, 0.15);\n"
"}\n"
"input[type=\"text\"], textarea {\n"
"  background: var(--bg);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 3px;\n"
"  color: var(--text);\n"
"  font-family: inherit;\n"
"  font-size: 12px;\n"
"  padding: 6px 8px;\n"
"  outline: none;\n"
"}\n"
"input[type=\"text\"]:focus, textarea:focus {\n"
"  border-color: var(--border-light);\n"
"}\n"
"/* Chat */\n"
"#chat-feed {\n"
"  background: var(--bg);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 3px;\n"
"  padding: 10px;\n"
"  height: 360px;\n"
"  overflow-y: auto;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  gap: 6px;\n"
"  margin-bottom: 10px;\n"
"}\n"
".chat-line {\n"
"  font-size: 12px;\n"
"  line-height: 1.4;\n"
"  word-break: break-word;\n"
"}\n"
".chat-meta {\n"
"  font-family: var(--mono);\n"
"  font-size: 11px;\n"
"  color: var(--text-dim);\n"
"  margin-right: 6px;\n"
"}\n"
".chat-nick {\n"
"  font-weight: 600;\n"
"  color: #fff;\n"
"  margin-right: 6px;\n"
"}\n"
".chat-form {\n"
"  display: flex;\n"
"  gap: 6px;\n"
"}\n"
"#chat-nick { width: 110px; font-family: var(--mono); font-size: 11px; }\n"
"#chat-text { flex: 1; }\n"
"/* Notes */\n"
".note-item {\n"
"  background: var(--surface);\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 3px;\n"
"  padding: 10px 12px;\n"
"  margin-bottom: 8px;\n"
"}\n"
".note-header {\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: baseline;\n"
"  margin-bottom: 6px;\n"
"}\n"
".note-title { font-weight: 600; font-size: 13px; color: #fff; }\n"
".note-meta { font-family: var(--mono); font-size: 11px; color: var(--text-muted); }\n"
".note-burn-badge { color: var(--warn); font-family: var(--mono); font-size: 10px; border: 1px solid rgba(217, 119, 6, 0.4); padding: 1px 4px; border-radius: 2px; margin-left: 6px; }\n"
".note-body {\n"
"  font-family: var(--mono);\n"
"  font-size: 11px;\n"
"  background: var(--bg);\n"
"  padding: 8px;\n"
"  border: 1px solid var(--border);\n"
"  border-radius: 2px;\n"
"  white-space: pre-wrap;\n"
"  word-break: break-word;\n"
"  color: #c9d1d9;\n"
"  max-height: 200px;\n"
"  overflow-y: auto;\n"
"}\n"
".note-footer {\n"
"  display: flex;\n"
"  justify-content: flex-end;\n"
"  gap: 6px;\n"
"  margin-top: 6px;\n"
"}\n"
"/* Tables */\n"
"table {\n"
"  width: 100%;\n"
"  border-collapse: collapse;\n"
"  font-size: 12px;\n"
"}\n"
"th, td {\n"
"  text-align: left;\n"
"  padding: 6px 8px;\n"
"  border-bottom: 1px solid var(--border);\n"
"}\n"
"th {\n"
"  font-family: var(--mono);\n"
"  font-size: 11px;\n"
"  font-weight: 500;\n"
"  color: var(--text-muted);\n"
"}\n"
"td.mono { font-family: var(--mono); font-size: 11px; }\n"
"td.actions { text-align: right; white-space: nowrap; }\n"
"/* Meter */\n"
".storage-bar {\n"
"  background: var(--bg);\n"
"  border: 1px solid var(--border);\n"
"  height: 6px;\n"
"  border-radius: 2px;\n"
"  overflow: hidden;\n"
"  margin: 6px 0;\n"
"}\n"
".storage-fill {\n"
"  background: var(--text);\n"
"  height: 100%;\n"
"  width: 0%;\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div class=\"brand\">PIRATEBOX</div>\n"
"  <div class=\"header-meta\" id=\"header-meta\">192.168.4.1 &middot; 0 clients</div>\n"
"</header>\n"
"\n"
"<nav>\n"
"  <button class=\"nav-btn active\" onclick=\"setTab('chat')\">Chat</button>\n"
"  <button class=\"nav-btn\" onclick=\"setTab('notes')\">Notes</button>\n"
"  <button class=\"nav-btn\" onclick=\"setTab('files')\">Files</button>\n"
"  <button class=\"nav-btn\" onclick=\"setTab('system')\">System</button>\n"
"</nav>\n"
"\n"
"<!-- CHAT -->\n"
"<div id=\"tab-chat\" class=\"tab active\">\n"
"  <div id=\"chat-feed\"></div>\n"
"  <form class=\"chat-form\" onsubmit=\"postChat(event)\">\n"
"    <input type=\"text\" id=\"chat-nick\" placeholder=\"Handle\" maxlength=\"16\">\n"
"    <input type=\"text\" id=\"chat-text\" placeholder=\"Message\" maxlength=\"200\" required autocomplete=\"off\">\n"
"    <button type=\"submit\" class=\"btn btn-primary\">Send</button>\n"
"  </form>\n"
"</div>\n"
"\n"
"<!-- NOTES -->\n"
"<div id=\"tab-notes\" class=\"tab\">\n"
"  <div class=\"card\">\n"
"    <form onsubmit=\"postNote(event)\" style=\"display:flex;flex-direction:column;gap:6px;\">\n"
"      <div style=\"display:flex;gap:6px;\">\n"
"        <input type=\"text\" id=\"note-title\" placeholder=\"Subject\" maxlength=\"40\" required style=\"flex:1;\">\n"
"        <input type=\"text\" id=\"note-nick\" placeholder=\"Author\" maxlength=\"16\" style=\"width:110px;\">\n"
"      </div>\n"
"      <textarea id=\"note-content\" rows=\"3\" placeholder=\"Text content\" required></textarea>\n"
"      <div style=\"display:flex;justify-content:space-between;align-items:center;\">\n"
"        <label style=\"font-size:11px;color:var(--text-muted);display:flex;align-items:center;gap:4px;cursor:pointer;\">\n"
"          <input type=\"checkbox\" id=\"note-burn\"> Burn after reading\n"
"        </label>\n"
"        <button type=\"submit\" class=\"btn btn-primary\">Post Note</button>\n"
"      </div>\n"
"    </form>\n"
"  </div>\n"
"  <div id=\"notes-list\"></div>\n"
"</div>\n"
"\n"
"<!-- FILES -->\n"
"<div id=\"tab-files\" class=\"tab\">\n"
"  <div class=\"card\" style=\"display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;\">\n"
"    <input type=\"file\" id=\"file-input\" style=\"display:none;\" onchange=\"uploadFile()\">\n"
"    <button type=\"button\" class=\"btn btn-primary\" onclick=\"document.getElementById('file-input').click()\">Upload File</button>\n"
"    <span id=\"upload-meta\" class=\"header-meta\"></span>\n"
"  </div>\n"
"  <div class=\"card\" style=\"padding:0;overflow-x:auto;\">\n"
"    <table>\n"
"      <thead>\n"
"        <tr>\n"
"          <th>NAME</th>\n"
"          <th>SIZE</th>\n"
"          <th style=\"text-align:right;\">ACTION</th>\n"
"        </tr>\n"
"      </thead>\n"
"      <tbody id=\"files-tbody\"></tbody>\n"
"    </table>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- SYSTEM -->\n"
"<div id=\"tab-system\" class=\"tab\">\n"
"  <div class=\"card\">\n"
"    <div class=\"card-title\">Internal Flash Storage (SPIFFS)</div>\n"
"    <div class=\"storage-bar\"><div id=\"storage-bar-fill\" class=\"storage-fill\"></div></div>\n"
"    <div class=\"header-meta\" id=\"storage-detail\">-- / -- KB</div>\n"
"  </div>\n"
"\n"
"  <div class=\"card\" style=\"padding:0;overflow-x:auto;\">\n"
"    <div class=\"card-title\" style=\"padding:8px 8px 0 8px;\">Connected Station Radar</div>\n"
"    <table>\n"
"      <thead>\n"
"        <tr><th>MAC ADDRESS</th><th>RSSI</th><th>PROXIMITY</th></tr>\n"
"      </thead>\n"
"      <tbody id=\"radar-tbody\"><tr><td colspan=\"3\" style=\"color:var(--text-muted);text-align:center;padding:10px;\">No stations connected</td></tr></tbody>\n"
"    </table>\n"
"  </div>\n"
"\n"
"  <div class=\"card\" style=\"padding:0;margin-top:12px;\">\n"
"    <div class=\"card-title\" style=\"padding:8px 8px 0 8px;\">Silicon Telemetry</div>\n"
"    <table>\n"
"      <tbody>\n"
"        <tr><th>SSID</th><td class=\"mono\">PirateBox - Offline Network</td></tr>\n"
"        <tr><th>AP IP</th><td class=\"mono\">192.168.4.1</td></tr>\n"
"        <tr><th>CPU Architecture</th><td class=\"mono\" id=\"stat-cpu\">Xtensa Dual-Core @ 240 MHz</td></tr>\n"
"        <tr><th>Free RAM (Current / Min)</th><td id=\"stat-ram\" class=\"mono\">--</td></tr>\n"
"        <tr><th>Uptime</th><td id=\"stat-uptime\" class=\"mono\">--</td></tr>\n"
"      </tbody>\n"
"    </table>\n"
"  </div>\n"
"  <div style=\"display:flex;gap:8px;margin-top:12px;\">\n"
"    <button type=\"button\" class=\"btn btn-danger\" onclick=\"clearChat()\">Clear Chat Log</button>\n"
"    <button type=\"button\" class=\"btn\" onclick=\"fetchStats()\">Refresh</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script>\n"
"let activeTab = 'chat';\n"
"let lastMsgCount = 0;\n"
"let ws = null;\n"
"\n"
"function connectWS() {\n"
"  try {\n"
"    ws = new WebSocket('ws://' + location.host + '/ws');\n"
"    ws.onmessage = (e) => {\n"
"      try {\n"
"        const data = JSON.parse(e.data);\n"
"        if (data.type === 'clear') {\n"
"          document.getElementById('chat-feed').innerHTML = '';\n"
"          lastMsgCount = 0;\n"
"        } else if (data.msg) {\n"
"          appendChatLine(data);\n"
"        }\n"
"      } catch(err) {}\n"
"    };\n"
"    ws.onclose = () => { setTimeout(connectWS, 2000); };\n"
"  } catch(e) {}\n"
"}\n"
"connectWS();\n"
"\n"
"function setTab(tab) {\n"
"  activeTab = tab;\n"
"  document.querySelectorAll('.tab').forEach(el => el.classList.remove('active'));\n"
"  document.querySelectorAll('.nav-btn').forEach(el => el.classList.remove('active'));\n"
"  document.getElementById('tab-' + tab).classList.add('active');\n"
"  event.currentTarget.classList.add('active');\n"
"  if (tab === 'chat') fetchChat();\n"
"  if (tab === 'notes') fetchNotes();\n"
"  if (tab === 'files') fetchFiles();\n"
"  if (tab === 'system') fetchStats();\n"
"}\n"
"\n"
"function getTimestamp() {\n"
"  const d = new Date();\n"
"  return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0');\n"
"}\n"
"\n"
"const nickInput = document.getElementById('chat-nick');\n"
"const noteNickInput = document.getElementById('note-nick');\n"
"let handle = localStorage.getItem('pb_handle') || 'user' + Math.floor(100 + Math.random() * 900);\n"
"nickInput.value = handle;\n"
"noteNickInput.value = handle;\n"
"nickInput.onchange = () => { localStorage.setItem('pb_handle', nickInput.value); noteNickInput.value = nickInput.value; };\n"
"noteNickInput.onchange = () => { localStorage.setItem('pb_handle', noteNickInput.value); nickInput.value = noteNickInput.value; };\n"
"\n"
"function appendChatLine(m) {\n"
"  const feed = document.getElementById('chat-feed');\n"
"  const row = document.createElement('div');\n"
"  row.className = 'chat-line';\n"
"  row.innerHTML = `<span class=\"chat-meta\">${m.time}</span><span class=\"chat-nick\">${escapeHtml(m.nick)}:</span><span>${escapeHtml(m.msg)}</span>`;\n"
"  feed.appendChild(row);\n"
"  feed.scrollTop = feed.scrollHeight;\n"
"}\n"
"\n"
"async function fetchChat() {\n"
"  try {\n"
"    const res = await fetch('/api/chat');\n"
"    const data = await res.json();\n"
"    const feed = document.getElementById('chat-feed');\n"
"    feed.innerHTML = '';\n"
"    data.forEach(m => appendChatLine(m));\n"
"    lastMsgCount = data.length;\n"
"  } catch(e) {}\n"
"}\n"
"\n"
"async function postChat(e) {\n"
"  e.preventDefault();\n"
"  const input = document.getElementById('chat-text');\n"
"  const msg = input.value.trim();\n"
"  if (!msg) return;\n"
"  const nick = nickInput.value.trim() || 'anonymous';\n"
"  const time = getTimestamp();\n"
"  input.value = '';\n"
"\n"
"  const payload = JSON.stringify({ nick, msg, time });\n"
"  if (ws && ws.readyState === WebSocket.OPEN) {\n"
"    ws.send(payload);\n"
"  } else {\n"
"    await fetch('/api/chat', {\n"
"      method: 'POST',\n"
"      headers: { 'Content-Type': 'application/json' },\n"
"      body: payload\n"
"    });\n"
"    fetchChat();\n"
"  }\n"
"}\n"
"\n"
"async function clearChat() {\n"
"  if (!confirm('Clear all chat messages?')) return;\n"
"  await fetch('/api/chat/clear', { method: 'POST' });\n"
"  fetchChat();\n"
"}\n"
"\n"
"async function fetchNotes() {\n"
"  try {\n"
"    const res = await fetch('/api/drops');\n"
"    const data = await res.json();\n"
"    const list = document.getElementById('notes-list');\n"
"    list.innerHTML = '';\n"
"    if (!data.length) {\n"
"      list.innerHTML = '<div class=\"card\" style=\"color:var(--text-muted);text-align:center;\">No notes recorded.</div>';\n"
"      return;\n"
"    }\n"
"    data.forEach(n => {\n"
"      const card = document.createElement('div');\n"
"      card.className = 'note-item';\n"
"      const burnTag = n.burn ? '<span class=\"note-burn-badge\">BURN ON READ</span>' : '';\n"
"      card.innerHTML = `\n"
"        <div class=\"note-header\">\n"
"          <span class=\"note-title\">${escapeHtml(n.title)} ${burnTag}</span>\n"
"          <span class=\"note-meta\">${escapeHtml(n.nick)} &middot; ${n.time}</span>\n"
"        </div>\n"
"        <div class=\"note-body\" id=\"note-body-${n.id}\">${n.burn ? '<i>Content protected. Click read to view and burn.</i>' : escapeHtml(n.content)}</div>\n"
"        <div class=\"note-footer\">\n"
"          ${n.burn ? `<button class=\"btn btn-primary\" onclick=\"viewAndBurnNote('${n.id}')\">Read Note</button>` : ''}\n"
"          <button class=\"btn btn-danger\" onclick=\"deleteNote('${n.id}')\">Delete</button>\n"
"        </div>\n"
"      `;\n"
"      list.appendChild(card);\n"
"    });\n"
"  } catch(e) {}\n"
"}\n"
"\n"
"async function viewAndBurnNote(id) {\n"
"  const res = await fetch('/api/drop?id=' + encodeURIComponent(id));\n"
"  if (res.ok) {\n"
"    const n = await res.json();\n"
"    const bodyEl = document.getElementById('note-body-' + id);\n"
"    if (bodyEl) bodyEl.innerHTML = escapeHtml(n.content) + '<br><br><span class=\"note-burn-badge\">DESTROYED FROM FLASH</span>';\n"
"  }\n"
"}\n"
"\n"
"async function postNote(e) {\n"
"  e.preventDefault();\n"
"  const title = document.getElementById('note-title').value.trim();\n"
"  const nick = noteNickInput.value.trim() || 'anonymous';\n"
"  const content = document.getElementById('note-content').value.trim();\n"
"  const burn = document.getElementById('note-burn').checked;\n"
"  const time = getTimestamp();\n"
"  if (!content) return;\n"
"  await fetch('/api/drops', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ title, nick, content, burn, time })\n"
"  });\n"
"  document.getElementById('note-title').value = '';\n"
"  document.getElementById('note-content').value = '';\n"
"  document.getElementById('note-burn').checked = false;\n"
"  fetchNotes();\n"
"}\n"
"\n"
"async function deleteNote(id) {\n"
"  await fetch('/api/drops?id=' + encodeURIComponent(id), { method: 'DELETE' });\n"
"  fetchNotes();\n"
"}\n"
"\n"
"async function fetchFiles() {\n"
"  try {\n"
"    const res = await fetch('/api/files');\n"
"    const data = await res.json();\n"
"    const tbody = document.getElementById('files-tbody');\n"
"    tbody.innerHTML = '';\n"
"    if (!data.length) {\n"
"      tbody.innerHTML = '<tr><td colspan=\"3\" style=\"color:var(--text-muted);text-align:center;padding:16px;\">No files in storage</td></tr>';\n"
"      return;\n"
"    }\n"
"    data.forEach(f => {\n"
"      const tr = document.createElement('tr');\n"
"      tr.innerHTML = `\n"
"        <td>${escapeHtml(f.name)}</td>\n"
"        <td class=\"mono\">${formatBytes(f.size)}</td>\n"
"        <td class=\"actions\">\n"
"          <a href=\"/api/download?file=${encodeURIComponent(f.name)}\" download class=\"btn\">Download</a>\n"
"          <button class=\"btn btn-danger\" onclick=\"deleteFile('${escapeHtml(f.name)}')\">Delete</button>\n"
"        </td>\n"
"      `;\n"
"      tbody.appendChild(tr);\n"
"    });\n"
"  } catch(e) {}\n"
"}\n"
"\n"
"async function uploadFile() {\n"
"  const picker = document.getElementById('file-input');\n"
"  if (!picker.files.length) return;\n"
"  const file = picker.files[0];\n"
"  const status = document.getElementById('upload-meta');\n"
"  status.innerText = 'Uploading ' + file.name + '...';\n"
"\n"
"  const xhr = new XMLHttpRequest();\n"
"  xhr.open('POST', '/api/upload?name=' + encodeURIComponent(file.name), true);\n"
"  xhr.upload.onprogress = (e) => {\n"
"    if (e.lengthComputable) {\n"
"      status.innerText = `${Math.round((e.loaded / e.total) * 100)}%`;\n"
"    }\n"
"  };\n"
"  xhr.onload = () => {\n"
"    picker.value = '';\n"
"    status.innerText = xhr.status === 200 ? 'Complete' : 'Failed';\n"
"    setTimeout(() => { status.innerText = ''; }, 2000);\n"
"    fetchFiles();\n"
"    fetchStats();\n"
"  };\n"
"  xhr.onerror = () => { status.innerText = 'Network error'; };\n"
"  xhr.send(file);\n"
"}\n"
"\n"
"async function deleteFile(name) {\n"
"  await fetch('/api/files?name=' + encodeURIComponent(name), { method: 'DELETE' });\n"
"  fetchFiles();\n"
"  fetchStats();\n"
"}\n"
"\n"
"async function fetchStats() {\n"
"  try {\n"
"    const res = await fetch('/api/stats');\n"
"    const d = await res.json();\n"
"    const clients = d.clients || 0;\n"
"    document.getElementById('header-meta').innerText = `192.168.4.1 &middot; ${clients} ${clients === 1 ? 'client' : 'clients'}`;\n"
"    document.getElementById('stat-ram').innerText = `${Math.round(d.free_heap / 1024)} KB / ${Math.round(d.min_heap / 1024)} KB min`;\n"
"    document.getElementById('stat-uptime').innerText = d.uptime_sec + 's';\n"
"    document.getElementById('stat-cpu').innerText = `Xtensa Dual-Core (${d.cores} cores) @ ${d.cpu_mhz} MHz (Rev ${d.rev})`;\n"
"\n"
"    const usedKb = Math.round(d.used_bytes / 1024);\n"
"    const totalKb = Math.round(d.total_bytes / 1024);\n"
"    const pct = totalKb > 0 ? Math.round((usedKb / totalKb) * 100) : 0;\n"
"    document.getElementById('storage-bar-fill').style.width = pct + '%';\n"
"    document.getElementById('storage-detail').innerText = `${usedKb} KB / ${totalKb} KB (${pct}%)`;\n"
"\n"
"    // Render Radar Table\n"
"    const rTbody = document.getElementById('radar-tbody');\n"
"    rTbody.innerHTML = '';\n"
"    if (d.stations && d.stations.length > 0) {\n"
"      d.stations.forEach(s => {\n"
"        const tr = document.createElement('tr');\n"
"        tr.innerHTML = `<td class=\"mono\">${s.mac}</td><td class=\"mono\">${s.rssi} dBm</td><td>${s.tier}</td>`;\n"
"        rTbody.appendChild(tr);\n"
"      });\n"
"    } else {\n"
"      rTbody.innerHTML = '<tr><td colspan=\"3\" style=\"color:var(--text-muted);text-align:center;padding:10px;\">No stations connected</td></tr>';\n"
"    }\n"
"  } catch(e) {}\n"
"}\n"
"\n"
"function formatBytes(bytes) {\n"
"  if (bytes < 1024) return bytes + ' B';\n"
"  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';\n"
"  return (bytes / 1048576).toFixed(2) + ' MB';\n"
"}\n"
"\n"
"function escapeHtml(s) {\n"
"  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');\n"
"}\n"
"\n"
"fetchChat();\n"
"fetchStats();\n"
"setInterval(() => {\n"
"  if (!ws || ws.readyState !== WebSocket.OPEN) {\n"
"    if (activeTab === 'chat') fetchChat();\n"
"  }\n"
"  fetchStats();\n"
"}, 3000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
