name: ESP32 CI/CD Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # local-chat
      - name: Run PlatformIO Build cho ChatRoom
        working-directory: ./local-chat
        run: pio run

      # new projcect here
      # - name: Run PlatformIO Build cho ChatRoom
      #   working-directory: ./local-chat
      #   run: pio run
